
public enum JointModes
{
    JOINT_MODE_RESET = 235,
    JOINT_MODE_SHUTTING_DOWN = 236, 
    JOINT_PART_D_CALIBRATION_MODE = 237, //(INTERNAL USE ONLY)
    JOINT_MODE_BACKDRIVE = 238,
    JOINT_MODE_POWER_OFF = 239,
    JOINT_MODE_NOT_RESPONDING = 245,
    JOINT_MODE_MOTOR_INITIALISATION = 246,
    JOINT_MODE_BOOTING = 247,
    JOINT_PART_D_CALIBRATION_ERROR_MODE = 248, //(INTERNAL USE ONLY)
    JOINT_MODE_BOOTLOADER = 249,
    JOINT_CALIBRATION_MODE = 250, //(INTERNAL USE ONLY)
    JOINT_MODE_VIOLATION = 251,
    JOINT_MODE_FAULT = 252,
    JOINT_MODE_RUNNING = 253,
    JOINT_MODE_IDLE = 255
}
