using UnityEngine;

public enum MessageTypes
{
    MESSAGE_TYPE_DISCONNECT = -1,
    MESSAGE_TYPE_ROBOT_STATE = 16,
    MESSAGE_TYPE_ROBOT_MESSAGE = 20,
    MESSAGE_TYPE_HMC_MESSAGE = 22,
    MESSAGE_TYPE_MODBUS_INFO_MESSAGE = 5,
    MESSAGE_TYPE_SAFETY_SETUP_BROADCAST_MESSAGE = 23,
    MESSAGE_TYPE_SAFETY_COMPLIANCE_TOLERANCES_MESSAGE = 24,
    MESSAGE_TYPE_PROGRAM_STATE_MESSAGE = 25
}
